import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { getServerSession } from "next-auth";
import { authOptions } from "@/app/api/auth/[...nextauth]/route";
import { redirect } from "next/navigation";
import Image from "next/image";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession(authOptions);
  if (!session) {
    return redirect("/");
  }

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <main className="flex min-h-screen">
          <aside className='bg-emerald-900/60 p-4 w-48'>
            an aside
            <div className="rounded-full overflow-hidden aspect-square w-30 mx-auto">
              <Image src={session.user.image} alt="user image" width={256} height={256} />
            </div>
            <nav className="flex flex-col text-center mt-8 gap-4">
              <Link href="/account">Settings</Link>
              <Link href="/analytics">Analytics</Link>
            </nav>
          </aside>
          <div className="p-6 max-w-4xl mx-auto">
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
