import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { getServerSession } from "next-auth";
import { authOptions } from "@/app/api/auth/[...nextauth]/route";
import { redirect } from "next/navigation";
import Image from "next/image"
import AppSidebar from "@/components/layout/AppSidebar";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function AppTemplate({ children }) {

  const session = await getServerSession(authOptions);
  if (!session) {
    return redirect("/");
  }

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Toaster/>
        <main className="flex min-h-screen">
          <aside className='bg-emerald-900/60 p-4 pt-8 w-50'>
            <div className="rounded-full overflow-hidden aspect-square w-30 mx-auto">
              <Image src={session.user.image} alt="user image" width={256} height={256} />
            </div>
            <div className="text-center">
              <AppSidebar/>
            </div>
          </aside>
          <div className="grow">
            <div className="bg-white m-8 p-4 shadow rounded-lg">
              {children}
            </div>

          </div>
        </main>
      </body>
    </html>
  );
}
